### ISSUE TITLE
Allow dictionary-like getters on result objects

### ISSUE THREAD

**Issue by sdcoffey** [braintree/braintreehttp_python#1]
### Issue description

Result objects should have dictionary-like getters to avoid try/except blocks as logical flow when the shape of a response is not known.

Example: a json response like 

```json
{
    "some_key": {
        "nested_key": "nested_value"
    }
}
```
If we don't know the shape of the response, we'll have code like:
```python

nested_key = None
try:
    nested_key = response.result.some_key.nested_key
except AttributeError:
    pass
```

Better:
```python
nested_key = response.result.some_key.get('nested_key', None)
```

**Comment by shulcsm** [comment]
I have similar issue. There should be a way to access raw/original payload. Why is `construct_object` even a thing?

Edit: #3 seems to be same issue

**Comment by sdcoffey** [comment]
Hey @shulcsm,

We construct objects from HTTP results to allow for convenient dot notation access to results. I've submitted a [PR](https://github.com/braintree/braintreehttp_python/pull/4) for supporting the index operator and the `in` operator on result objects. Take a look and let me know what you think.

**Comment by shulcsm** [comment]
Hey, it's been a could you tag this and push downstream to PayPal-Python-SDK?
