### ISSUE TITLE
pypi version is outdated (0.5.0)

### ISSUE THREAD

**Issue by biodiv** [braintree/braintreehttp_python#6]
https://pypi.org/project/braintreehttp/#history

key elements like the `Result` class are missing in the pypi version. Updating the pypi version would be nice.

**Comment by crookedneighbor** [comment]
Looks like v0.5.0 is the latest release: https://github.com/braintree/braintreehttp_python/releases/tag/0.5.0

The Result stuff has not been released yet. The PyPi version will be updated when the next release happens.

**Comment by biodiv** [comment]
Thanks for the insight. I would appreciate an updated release. The current release is from April 2018. The `Result` object is convenient, eg because it offers a `.dict()` method which one can use to directly store data in postgres JSON columns.
